[package]
name = "RTiOW"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.2"
palette = "0.7.3"
rand = "0.8.5"
futures = "0.3.31"
tokio = { version = "1.40.0", features = ["full"] }